name: Swift DocC
 
on:
  push:
    # If you wanted to only trigger this flow on certain branches,
    # specify them here in 
    branches:
      - 'main'
    # alternatively, you can trigger docs only on new tags pushed:
    # tags:
      # - '[0-9]+.[0-9]+.[0-9]+'
 
# `concurrency` specifices how this action is run. 
# Setting concurrency group makes it so that only one build process runs at a time.
concurrency:
  group: "pages"
  cancel-in-progress: false
 
env:
  # Build target specifies which target in your Swift Package to build documentation for.
  # To build all targets, remove this env variable, 
  # and remove --target arg in the building step below.
  BUILD_TARGET: JWSETKit
 
jobs: 
  build:
    runs-on: macos-13

    permissions:
      contents: 'read'
      id-token: 'write'
      pages: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Build the DocC website using swiftPM.
    - name: Build docs with SwiftPM
      run: |
        swift package --allow-writing-to-directory ./docs \
        generate-documentation --target ${BUILD_TARGET} \
        --output-path ./docs \
        --disable-indexing \
        --transform-for-static-hosting \
        --hosting-base-path JWSETKit
 
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: 'docs'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
 